### ISSUE TITLE
Kan inte se event som reserv?

### ISSUE THREAD

**Issue by andersonjonathan** [I-sektionen/i-portalen#498]
Sjukt oklar bugg. En kompis var anmäld som reserv till Intervjucase med Accenture och ville avanmäla sig. Men när han gick in i eventet blev det bara vitt (typ som när man la upp en bild förut), dock kunde jag som inte var anmäld gå in i evenemanget. Jag tog bort honom från databasen (anmälningstiden inte ute), och efter det kunde han se eventet. Sen testade vi igen att han anmälde sig som reserv och det blev vitt igen. Så verkar vara en bugg att man inte kan se event som man är anmäld som reserv till! :S 
Kan dock inte sitta och testa/buggsöka just nu!

**Comment by JessieVicky** [comment]
fixad i pull requesten #596
