### ISSUE TITLE
Lägg upp gamla ipikure nummer på iportalen

### ISSUE THREAD

**Issue by andersonjonathan** [I-sektionen/i-portalen#502]
Antar att en egen html sida på i-portalen är smidigaste lösningen och att lägga det under typ tjänster?

**Comment by Arvidrockert** [comment]
Detta skall vara under ipikurés "föreningssida" på i-portalen. En knapp som gör det möjligt för ipikure själva att ladda upp en thumbnailbild och en länk skall finnas. Och sedan visas alla gamla nummer längst ned.

**Comment by ElonB** [comment]
Ipikuré har gamla nummer på sin hemsida och i Dropbox.
