### ISSUE TITLE
Lägg till CM under "sektionen"

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#523]
I topmenyn, under "sektionen" bör Clubmästeriet också finnas med. Deras länk bör dock inte gå till en "utskotts-sida" som dem andra, den bör istället gå till deras hemsida clubmasteriet.se

**Comment by ElonB** [comment]
Ordnat, se [länk](https://www.i-portalen.se/organisations/Clubm%C3%A4steriet/)
