### ISSUE TITLE
Add new sponsor

### ISSUE THREAD

**Issue by andersonjonathan** [I-sektionen/i-portalen#525]
Hej, 

Vi från Näru har snart en ny samarbetspartner och det jag undrar är ifall följande går bra att lägga upp på I-portalen: 

De önskar länkning till följande länk:https://www.se.capgemini-consulting.com/careers/start-your-career-with-us

 

￼

säg gärna till ifall formatet på bilden eller länken ej fungerar bra. 

Vänligen, 

Erik Andersson

070 772 8001

Näru

**Comment by Arvidrockert** [comment]
Är detta löst? Jag ser att capgemini finns som sammarbetspartner på i-portalen och länken går som ovan. Ska jag sätta detta på "done"?
