### ISSUE TITLE
Text formatting not working as intended on "studievägledningens FAQ"

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#555]
"Vi har en önskan om att göra att svaren till "Studievägledningens FAQ" kan ha formatering. Det mest akuta är att få till så att man kan göra radbrytningar i stycken.

Såhär ser det ut idag (vi har fyllt på i topic Studievägledningen hittills): https://www.i-portalen.se/faq/studievagledningen/

Jag har provat lägga in textformatering som ni beskriver i er Användarmanual utan att det fungerar.

Efter att jag i våras började lägga in frågor där upptäckte jag att det inte såg bra ut och var svårläsligt, så de andra frågorna har fått vänta."

I would like for this to be prioritized since it has been unresolved for quite a while.

**Comment by robinbouveng** [comment]
Hur ser status ut på detta? Ser att det finns en lösning av issuen men det verkar inte fungera som det ska på i-portalen. Radbryt verkar dock fungera på development.i-portalen (se "Hur många poäng måste jag ha i tekniska inriktningen?" under "Val av teknisk inriktning"-titeln och jämför med riktiga i-portalen).

Fick även nyligen ett uppdaterat FAQ-dokument med redigerad text som skall läggas in när detta är klart.

[FAQ I-portalen.docx](https://github.com/I-sektionen/i-portalen/files/714223/FAQ.I-portalen.docx)

**Comment by AntonRevin** [comment]
Lösningen väntar på att vi ska lösa några tekniska problem innan blir live.

Själva informationen i FAQ:n ändras i admin sidorna (vet inte vad praxis är gällande detta). @ElonB ?

**Comment by robinbouveng** [comment]
Okej toppen, då vet jag. 

Jag eller admins kan lägga in informationen i FAQ:n när lösningen är klar så slipper ni sitta med detta!
