### ISSUE TITLE
Add information under "Sektionen"

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#556]
Due to a contract we are obliged to provide this solution:

In the expandable menu of "Sektionen" add another item called: Sektionens vänner

This should be a link to a new page (very much like any other organisation). That page should contain the logo of "börsgruppen" as well as the logo of "Sektionen ELIN". Those pictures should link to their respective websites http://www.borsgruppen.se/ and http://elin.se/.

**Comment by webmaester** [comment]
Now live and mail sen to Stasik. 
https://www.i-portalen.se/organisations/Sektionens%20v%C3%A4nner/
