### ISSUE TITLE
Sponsors not showing in firefox

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#569]
From my end (tested on several computers) the sponsors do not show in the right coloumn of i-portalen when using firefox to access i-portalen.

**Comment by andersonjonathan** [comment]
Pics or it didn't happen... 
Jag ser dem nämligen i firefox här (Ubuntu16.06, Firefox 49.0).
Kan det vara något annat problem, har du tex någon adblocker i firefox?

**Comment by Arvidrockert** [comment]
Okej! Jag är säker på att det var ett problem, kollade till och med med andra, men då verkar det vara löst! Du kan stänga issuen när du läst detta @andersonjonathan !
