### ISSUE TITLE
[important] error in booking of i-bilen

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#571]
"Jag har upptäckt ett fel i bokningen för I-bilen på I-portalen. I schemat där man bokat bilen har alla bokningar flyttas fram en dag, medan de rätta tiderna för bokningar finns på min administratörssida och under "mina bokningar" för de som har bokat bilen. Har du/ni tid att titta något på det här under dagen? " - I-bilen ansvarig (Lisa Wedlund, bilen@isektionen.se)

När det är åtgärdad, maila gärna det till: 
bilen@isektionen.se

**Comment by andersonjonathan** [comment]
Jag tycker det ser rätt ut eller? Kan du ta ett par skärmdumpar på där det är fel?

**Comment by Arvidrockert** [comment]
Jag har pratat med personen som anmälde problemet och hon kunde inte hitta problemet längre! Vi betraktar det löst, du kan stänga issuen när du läst!
