### ISSUE TITLE
Change logo on i-portalen

### ISSUE THREAD

**Issue by Arvidrockert** [I-sektionen/i-portalen#578]
We have changed the i-sektionen-logo. The new one now contains "Linköpings universitet" instead of "Linköpings tekniska högskola". The new logo should be changed on all places where this occurs. 

The image files can be found on the file storage:
https://www.dropbox.com/home/I-Portalens%20filarkiv/Grafisk%20Profil

**Comment by ElonB** [comment]
Changed logos on i-portalen and  isektionen.
