### ISSUE TITLE
Information om event saknas när anmäld som reserv

### ISSUE THREAD

**Issue by StahlErik** [I-sektionen/i-portalen#591]
När man är anmäld som reserv till ett event (dvs det är fullt) så syns inte längre någon information om eventet, bara en tom sida.
![123](https://cloud.githubusercontent.com/assets/22325129/22780615/98849c32-eebf-11e6-8695-88c67e3c7681.png)

**Comment by JessieVicky** [comment]
samma problem som #498

**Comment by JessieVicky** [comment]
hahaha Anton hittade en typo som var grunden till problemet
