### ISSUE TITLE
500 error när man klickar på "mina events"

### ISSUE THREAD

**Issue by robinbouveng** [I-sektionen/i-portalen#597]
Kan konfirmera att det gäller för fler personer än mig själv, vet inte om det gäller alla dock

**Comment by AntonRevin** [comment]
Tror att detta är fixat och väntar på att merge:as in. ping @JessieVicky ?

**Comment by JessieVicky** [comment]
@robinbouveng "Mina Event" som finns i headern, eller den under "innehåll"?
Kan du också printscreena ifall det står ngt mer än 500 error?

**Comment by robinbouveng** [comment]
@JessieVicky "Mina event" som finns i headern. Den under "innehåll" fungerar precis som den ska. Bifogar en bild nedan, såg även att det ser ut som jag är utloggad när felet uppstår!
