### ISSUE TITLE
Informativ sida om programvaror

### ISSUE THREAD

**Issue by robinbouveng** [I-sektionen/i-portalen#621]
Vi hade tidigare en licens till ett plug-in till excel som heter think-cell. Ett krav för att få denna licens gratis var att ha en informativ sida om programvaran på vår hemsida. Fick nyligen det påpekat av flera studenter att vår licens blivit ogiltig, då den informativa sidan låg på gamla i-portalen och därmed nu är borta.

Mitt förslag är att lägga till en länk "Programvaror" i den vänstra kolumnen under "tjänster & studier" som leder till en informativ sida om programvaran. Bifogar den text som behövs.
[think-cell.docx](https://github.com/I-sektionen/i-portalen/files/951273/think-cell.docx)

Vad tror ni om detta?

**Comment by andersonjonathan** [comment]
Vad har vi för programvaror?

**Comment by robinbouveng** [comment]
Uppdaterade beskrivningen, se ovan :)

**Comment by robinbouveng** [comment]
LiU-IT vill inte signera avtalet med think-cell gällande detta längre av diverse anledningar. Denna issuen kan därför raderas/läggas åt sidan tills vidare om ni vill.
