### ISSUE TITLE
Underlätta ingresskrivandet för artiklar

### ISSUE THREAD

**Issue by erikkarvonen** [I-sektionen/i-portalen#631]
### Sammafattning
Fått förslag från näru att man underlätta ingresskrivandet vid skapande av en ny artikel. Vi har en max-count på 160 tecken för ingressen men står ingenstans hur många personen själv har skrivit, om man har för många står det endast "för många tecken." 

### Workaround
Kanske lägga in en realtids räknare så att användaren vet hur många tecken som den har skrivit. Ex. en rad under textboxen med "113/160 tecken."
Alternativt skriva ut hur många tecken användaren skrivit för mycket. Ex: "58 tecken för mycket."

**Comment by AntonRevin** [comment]
Tycker jag låter som en alldeles utmärkt idé! En räknare på formatet "xxx/160" vore nog snyggast.

**Comment by AntonRevin** [comment]
@hackergustav @Jeshe316 Status på denna?

**Comment by hackergustav** [comment]
Ska vara klart!

Den 9 jan. 2018 1:42 em skrev "AntonR" <notifications@github.com>:
