### ISSUE TITLE
Lägga till ett styckte text i kalender-fliken

### ISSUE THREAD

**Issue by robinbouveng** [I-sektionen/i-portalen#633]
Föreningar/utskott har påpekat att det borde länkas till riktlinjerna för sektionens kalender på kalender-fliken på i-portalen. Vi skulle därför vilja att texten på denna flik ändras till:

"Nedan visas en kalender med sektionens aktuella evenemang. För att se alla evenemang för hela terminen finns en Google-kalender som kan läggas in i valfritt kalenderprogram med hjälp av följande länk. Notera att Google-kalendern innehåller preliminära datum där evenemang läggs in löpande.

Riktlinjer för hur kalendern ska användas (för föreningar, utskott och projektgrupper) finns här."

Det är alltså bara sista stycket vi önskar lägga till, och vi tänker att ordet "här" ska länka till följande länk:
https://www.dropbox.com/home/I-Portalens%20filarkiv/Policys?preview=Riktlinjer+Sektionsaktivas+kalender.pdf

**Comment by GSvensk** [comment]
@robinbouveng Länken är inte tillgänglig för alla så det går inte att se pdf:en den länkar till, länken måste göras publik.

**Comment by robinbouveng** [comment]
Sorry måste missat det. Funkar denna?
https://www.dropbox.com/s/levcxflounpgis2/Riktlinjer%20Sektionsaktivas%20kalender.pdf?dl=0
